### ISSUE TITLE
Int2f/1203 not returning DOS data segment with gcc built kernel

### ISSUE THREAD

**Issue by andrewbird** [FDOS/kernel#11]
Dosemu2's redirector makes use of int2f/1203 to find DOS's data segment. Unfortunately on GCC builds from git (and maybe Borland 3) this doesn't return a valid result, however the released kernels on FreeDOS 1.00/1.10/1.20 work fine in this regard. This leads to a failure to boot on Dosemu2 as it corrupts DOS memory whilst trying to initialise the redirector.

I've attached a simple binary that could be used to call the function, it should be run in a debugger to see the result as it doesn't print anything itself.
```asm
.text                                                                           
.code16                                                                         
                                                                                
    .globl  _start16                                                            
_start16:                                                                       
                                                                                
    push    %cs                                                                 
    pop     %ds                                                                 
                                                                                
    movw    $0x1203, %ax                                                        
    int     $0x2f                                                               
    nop                                                                         
                                                                                
exit:                                                                           
    movb    $0x4c, %ah                                                          
    int     $0x21                                                               
```

[int2f12p.zip](https://github.com/FDOS/kernel/files/3922491/int2f12p.zip)

This may be related to #3 which was never resolved.

**Comment by tkchia** [comment]
Hello @andrewbird,

Well... after looking at the `int 0x2f` code a bit more closely, I now think it is because `int2F_12_handler (r)` (in `inthndlr.c`) is trying to _output_ values to the caller by passing "back" an input parameter `r`.

This turns out to be an iffy thing to do --- GCC basically assumes that input parameter values can be treated as "dead" upon return (and this is kind of reasonable, if some input parameters are passed in call-clobbered registers).  So it may throw away attempts to store stuff into the `r` structure.

A quick-and-dirty fix would be to mark the parameter `volatile`, e.g.
```
VOID ASMFUNC int2F_12_handler(struct int2f12regs r) ...
```

However, my preferred fix is to change the interface to make it accept a pointer, e.g.
```
VOID ASMFUNC int2F_12_handler(struct int2f12regs *pr) ...
```
with corresponding changes on the `int2f.asm` end.

> This may be related to https://github.com/FDOS/kernel/issues/3 which was never resolved.

t seems I had missed this earlier report, for some reason --- my apologies.

Thank you!

**Comment by andrewbird** [comment]
> It seems I had missed this earlier report, for some reason

I probably made the bug report too big and wordy to generate anybody's interest, this time I tried to distil it down to the bare minimum to describe the issue.

Thanks for looking at it, if you need anything else(testing potential fix etc) please let me know?

**Comment by tkchia** [comment]
Hello @andrewbird,

Thank you!  I have submitted a pull request to fix at least the `int 0x2f`, `ax` == `0x1203` case.

From what I see, there also seem to be similar issues with the implementation of `int 0x2f`, `ah` == `0x14`.  These can probably be fixed in the same ways.

**Comment by andrewbird** [comment]
Thanks! I'll give it a test on Dosemu2 to see if it stops FreeDOS the crashing on boot and let you know.

**Comment by andrewbird** [comment]
Sorry I forgot to mention in the bug report that with PR #12 this issue is fixed, thanks!
