### ISSUE TITLE
FDIMPLES crashes with current kernel

### ISSUE THREAD

**Issue by boeckmann** [FDOS/kernel#148]
I tested T2403 + current kernel build and noticed that FDIMPLES crashes reproducible after selecting packages and "clicking" on ok to install the packages. Because it works at least with kernel revisions up to 4th February 2024, chances are high that this is a kernel related problem.

I tested the last two commits, both fail:
https://github.com/FDOS/kernel/commit/c08313ab62ed236fc9a11f1c558cc335b93de30c
https://github.com/FDOS/kernel/commit/ea951d8136444e334f06a313465b5844f738354e

The following from 4th February works:
https://github.com/FDOS/kernel/commit/9a7d22701dce7b401025064da73c5860096c6102

I will try to find out the exact commit that broke it.

![Screenshot 2024-03-06 184347](https://github.com/FDOS/kernel/assets/6333969/e59d8590-0b0c-4272-b981-5cca7bec9365)

**Comment by boeckmann** [comment]
This is the first commit FDIMPLES is failing:
https://github.com/FDOS/kernel/commit/431be02b0a1067b89be1867103994dc34540e4c9

**Comment by shidel** [comment]
After talking with @boeckmann  during today's online get-together, I figured it may be helpful for me to comment here. 

After selecting packages to install or remove, FDIMPLES does a few things to make that happen. 

First, it goes through and relocates the packages actions into a list that was pre-allocated at program startup to exist just above the program itself. Then, it shrinks the amount of memory for the Heap and resizes its program memory block to just above the memory location of the action list. It then swaps interrupt vectors and uses DOS to execute the program which performs the installation and removal of packages.  Upon return to FDIMPLES, it swaps the interrupt vectors back, re-initializes its display driver and proceeds to the next action item. After the list is completed, FDIMPLES exits to DOS because it would not be safe to use the PASCAL heap after shrinking. 

The most interesting portion is the launching of the program that performs the package installation and removal.  That would be FDINST.COM. For an unknown reason, FDINST will not function as expected when launched directly from FDIMPLES. So as a stop gap solution, FDIMPLES creates a small batch file the to execute FDINST with the appropriate commands. Then executes COMMAND.COM to run the batch file. 

The requirement to go through COMMAND.COM for FDINST is very odd. The dos function call to execute a program the program under FDIMPLES are handled by a [Pascal Procedure](https://github.com/shidel/FDIMPLES/blob/492a2efbb5d0470dc34fe60bc3acaf5322153d65/SOURCE/FDIMPLES/QCrt/PASCAL/QDOS.PAS#L934)  and it's [Assembly Include](https://github.com/shidel/FDIMPLES/blob/492a2efbb5d0470dc34fe60bc3acaf5322153d65/SOURCE/FDIMPLES/QCrt/PASCAL/QDOS.PAS#L893). 

The portion of FDIMPLES that executes programs  using the  [Exec function](https://fd.lod.bz/rbil/interrup/dos_kernel/214b.html#2979) is for all intents the same used by [PGME](https://github.com/shidel/PGME/blob/391dc84a8d4dbb5cb6d58890c4728b1470e2538c/SOURCE/PGME/QUICKCRT/QDOS.PAS#L934). (Same libraries, just different versions). And that program has issues launching FDINST. But no problems with countless other programs. 

I discussed the issue of launching FDINST with Mateusz a couple times. However, I was unable to determine the cause. Or,  what the program was expecting that was not being provided when launched directly. 

So, it is possible that the kernel crash issue is caused by FDIMPLES. But as far as I can tell, the Exec code it uses is to spec. It is also possible that I or the documentation for the function is missing something. Or, even a bug in my code somewhere. 

It could also be a bug with the FreeCOM sub-shell used to execute FDINST indirectly. 

BTW. If you look at the code used to launch the package install/removal program and know what prevents FDIMPLES from launching FDINST directly, I'd really love to hear why. I would be great to remove that requirement. 

Jerome

**Comment by ecm-pushbx** [comment]
Could you upload / point to some files (eg your attempt for FDIMPLES to directly launch FDINST) and all exacting instructions for how to run (and how it is supposed to work)? If you do that I may look into it.

**Comment by shidel** [comment]
@ecm-pushbx, that would be great. I created an [Issue under the FDIMPLES ](https://github.com/shidel/FDIMPLES/issues/5#issue-2279738122)project.

**Comment by boeckmann** [comment]
Cross-reference to the FDINST.COM source: https://gitlab.com/FreeDOS/util/fdnpkg/-/tree/master/SOURCE/FDNPKG/

**Comment by dieymir** [comment]
That commit: [431be02](https://github.com/FDOS/kernel/commit/431be02b0a1067b89be1867103994dc34540e4c9)

Makes Norton Disk Doctor 8.0 and 4DOS 8.0 crash, too. Reverting it solvencia the problem.

**Comment by boeckmann** [comment]
@dieymir interesting, did you find a way to reproduce it with 4DOS? For me it crashes somewhat randomly with FDIMPLES, making it hard to debug.

Last time I looked at the mentioned commit I saw no obvious flaw. But I will have a second look. If we are unlucky, this commit triggers a bug somewhere else...

**Comment by shidel** [comment]
>For me it crashes somewhat randomly with FDIMPLES, making it hard to debug.

Assuming it is not a bug in FDIMPLES (and there very well could be), based on what FDIMPLES is doing while browsing packages, a bug in the kernel would need to be in one of 3 places. 

During the initial memory block allocation for the program which eventually causes the program to overwrite some critical piece of memory. This is very unlikely. More likely a lost pointer in the program would be the cause of such memory corruption. 

During the package browsing process, FDIMPLES check multiple paths on the hard disk and package install media for various files. This process uses the FindFirst/FindNext DOS functions. 

The program also opens, reads and closes multiple files. For example, installed metadata for a package, uninstalled metadata for available packages, package group index files, package contents listing files. It process all that information through a built-in caching system. Keeping everything it has correlated  until it starts getting low on memory. At that point, it starts discarding information it can do without until sufficient memory is freed to complete the task at hand. It also may abort the current task if the user navigates to another selection. 

All that is to say, the program is performing a lot of disk I/O using the directory and file functions. 

If the problem is actually on the kernel side, me thoughts would be possibly a corruption of a critical register like DS,SS,SP or BP. Since FDIMPLES is written in Pascal (with a lot of assembler for DOS calls), it does not care about most registers (other than the ones it needs) when returning from a DOS call.

Or, maybe bug in file reading that is not putting the contents where it is supposed to go. 

Or, maybe file handle allocation. 

Or, just a simple stack bug. 

But, all that is just guessing. Probably a bug in my program anyway. :-)

**Comment by dieymir** [comment]
> @dieymir interesting, did you find a way to reproduce it with 4DOS? For me it crashes somewhat randomly with FDIMPLES, making it hard to debug.
> 
> Last time I looked at the mentioned commit I saw no obvious flaw. But I will have a second look. If we are unlucky, this commit triggers a bug somewhere else...

Not difficult Change your SHELL in CONFIG.SYS it will crash as soon as it's run when booting. Reverting that change solves the problem.

**Comment by boeckmann** [comment]
The following looks wrong to me. This are the addresses of the device parameter blocks:
<img width="304" alt="Bildschirmfoto 2024-05-16 um 19 52 00" src="https://github.com/FDOS/kernel/assets/6333969/ebe211d8-2c3f-4cfd-9c37-aeecde7cd69f">

But MEM shows they are in a free region?
<img width="475" alt="Bildschirmfoto 2024-05-16 um 19 52 23" src="https://github.com/FDOS/kernel/assets/6333969/3ad2a3b1-5c15-4640-8e01-76bfe1b399c4">

**Comment by boeckmann** [comment]
I try to understand the memory handling during the boot process.

In PreConfig, memory gets allocated in the dynamic allocation area for DPBs (number as returned by init_disk()) via DynAlloc:
https://github.com/FDOS/kernel/blob/1b6de0fda6a24fdbf6f523da95cc04d0fab1204f/kernel/config.c#L355-L356

In update_dcb(), the memory gets allocated a second time via allocation Routine KernelAlloc:
https://github.com/FDOS/kernel/blob/1b6de0fda6a24fdbf6f523da95cc04d0fab1204f/kernel/main.c#L550-L557

KernelAlloc, however, also allocates in some BSS section of the kernel (NOT via a MCB), because memory subsystem it not fully initialized at this point:
https://github.com/FDOS/kernel/blob/1b6de0fda6a24fdbf6f523da95cc04d0fab1204f/kernel/config.c#L1980-L1990

first_mcb should be zero at this point, at least it is defined to be so, and before update_dcb() it is not touched, to my understanding:
https://github.com/FDOS/kernel/blob/1b6de0fda6a24fdbf6f523da95cc04d0fab1204f/kernel/kernel.asm#L517
So this would result in memory being allocated in the BSS section.

first_mcb is eventually initialized in PreConfig2:
https://github.com/FDOS/kernel/blob/1b6de0fda6a24fdbf6f523da95cc04d0fab1204f/kernel/config.c#L397

From the last line I deduce that the space DynAlloc() allocated seems to be permanently reserved?!? And it seems it is being protected from inclusion in the MCB range. But the memory KernelAlloc allocates at initial stage to my understanding is not, so will be eventually overwritten by later KernelAlloc calls.

Is this correct or did I miss anything?
